### ISSUE TITLE
Crash on non-standard characters in card name

### ISSUE THREAD

**Issue by amarillonmc** [AlphaKretin/bastion-bot#3]
Sometimes after a query is made, the bot will crash. It seems that more queries made in a session would make the possibility of a crash happens greater, up to the point where even a single randcard comment can crash the bot.

This is the error message that's displayed upon crashing.
```
`C:\bastion-bot-master>node bastion.js
URL for backup script source not found at config.scriptUrlBackup! Bastion will n
ot try to find an alternative to missing scripts!
Logged in as Star Duelist Haruchin! -<omitted>

C:\bastion-bot-master\node_modules\sql.js\js\sql.js:5
1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");f.ar
guments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=f);pr
ocess.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;});f.insp
ect=function(){return"[Emscripten Module object]"}}else if(fa)f.print||(f.print=
print),"undefined"!=typeof printErr&&(f.printErr=printErr),f.read="undefined"!=t
ypeof read?read:function(){throw"no read() available (jsc?)";},f.readBinary=func
tion(a){if("function"===


                                                               ^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\bastion-bot-master\bastion.js:457:20)
    at Request.self.callback (C:\bastion-bot-master\node_modules\request\request
.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\bastion-bot-master\node_modules\request\request.j
s:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\bastion-bot-master\node_modules\request\r
equest.js:1085:12)
    at Object.onceWrapper (events.js:313:30)`
```

Our server's situation is as follows:
The bot is configured to take 2 cdb files, one being cards.cdb, the other is a custom card cdb.
Both cdbs are confirmed working on the server.
they're hooked to different image/scripts repos on github.
While the bot is more likely to crash when a query regarding a custom card is made, sometimes queries featuring official cards will still crash the bot with the above exact same error message.

The server currently also has an instance of Simon running, but it seems not related to the crash since I tried running the bot in a server that only has the bot and the crash still happened while the same error is thrown.

EDIT:
Upon closer inspection based on the error message, I noticed that 
https://yugiohprices.com/api/get_card_prices/
is giving out 502 Bad Gateway errors when connected to as in the point of writing this issue.

**Comment by AlphaKretin** [comment]
It's hard to test an external API giving bad data, so feel free to re-open if I'm wrong about that commit fixing this.

**Comment by amarillonmc** [comment]
While the API problem seems to be fixed. The bot seems to crashes the same way when there's non-alphabet characters in the card name. (non-alphabet characters in other places seems to be fine)

_non-alphabet characters tested in this case being CJK characters and symbols._

**Comment by AlphaKretin** [comment]
https://puu.sh/ytDzz/95f192b0c3.png
https://puu.sh/ytDAl/564f16b587.png
I'm afraid I can't seem to replicate this issue... When you say it crashes the same way, you mean it has the same error message? If not, could you please post it, along with an example of a search that causes a crash?

**Comment by amarillonmc** [comment]
Nonono, this is what I mean.
https://i.imgur.com/lXS95Gg.png

Note how the card I searched has a `【O】`in its cardname in cdb?

**Comment by AlphaKretin** [comment]
Yeah, I understand now. Gimme a bit to prepare myself a database with that character in it for testing and I'll get back to you.

**Comment by amarillonmc** [comment]
You can also use any Chinese/Japanese cdbs for testing. grab them from Mercury233's repos.
https://github.com/moecube/ygopro-database
