### ISSUE TITLE
Permission system

### ISSUE THREAD

**Issue by AlphaKretin** [AlphaKretin/bastion-bot#38]
The rework of Bastion is nominally supposed to have a permission system, that can prevent certain roles from using certain commands in certain channels. However, I never really got there. I built a skeleton, but I haven't tested it in a long time, and I don't think it worked last time I did. It was also generally clumsy, tedious and unwieldy to set permissions, and it was missing other features I might want to include in a permission system. I need to redesign and reimplement the system from the ground up. The below list of features is not complete at this time, I will flesh it out in the process of redesigning the system.
- [ ] When Bastion joins a server, commands usability is set by some default values
- [ ] The server administrator can change permissions, including giving the permission to change permissions to other users e.g. moderators. This needs to follow Discord role hierarchy, e.g. you can only change the role permissions of someone with a lower role than your highest role with permission.
- [ ] Individual users can also be blacklisted
- [ ] Bastion admins can blacklist users globally
- [ ] In addition to commands, the system needs to affect the ability to search cards

**Comment by kevinlul** [comment]
With [Slash Commands](https://discord.com/developers/docs/interactions/application-commands), server administrators can manage the permissions for each command individually in the integration tab much like they would other Discord permissions on a per-role or per-channel basis.

**Comment by kevinlul** [comment]
> the system needs to affect the ability to search cards

No user demand for this. The current recommendation is to [deny Bastion View Channel](https://github.com/DawnbrandBots/bastion-bot#discord-permissions) if the message search is unwanted, and then if specific users should be allowed to search in a channel anyway, then they can be authorized to use `/search`.
