### ISSUE TITLE
Can't search for custom cards after newest update

### ISSUE THREAD

**Issue by amarillonmc** [AlphaKretin/bastion-bot#4]
Encounters this error:
`0|bastion  | You have triggered an unhandledRejection, you may have forgotten to
 catch a Promise rejection:
0|bastion  | TypeError: Cannot read property 'replace' of undefined
0|bastion  |     at searchCard (C:\bastion-bot-master\bastion.js:509:37)
0|bastion  |     at DiscordClient.<anonymous> (C:\bastion-bot-master\bastion.js:
413:5)
0|bastion  |     at emitMany (events.js:147:13)
0|bastion  |     at DiscordClient.emit (events.js:224:7)
0|bastion  |     at DiscordClient.handleWSMessage (C:\bastion-bot-master\node_mo
dules\discord.io\lib\index.js:1856:11)
0|bastion  |     at emitTwo (events.js:126:13)
0|bastion  |     at WebSocket.emit (events.js:214:7)
0|bastion  |     at Receiver.ontext (C:\bastion-bot-master\node_modules\ws\lib\W
ebSocket.js:841:10)
0|bastion  |     at C:\bastion-bot-master\node_modules\ws\lib\Receiver.js:536:18

0|bastion  |     at Receiver.applyExtensions (C:\bastion-bot-master\node_modules
\ws\lib\Receiver.js:371:5)`

(I'm using pm2 to run bastion if you're wondering)

This is the related content in config.
`	"dbs": {
		"en": [
			"cards.cdb", "cardsdiy3.cdb"
		]
	},`
dbMemory is using the default value.

**Comment by AlphaKretin** [comment]
Alright, I reckon I have the issue resolved, I'll just patch up another issue I noticed before making a commit.
