### ISSUE TITLE
Restore "Clock Lizard" CDB

### ISSUE THREAD

**Issue by AlphaKretin** [AlphaKretin/bastion-bot#50]
When Bastion's data sources were changed over to Project Ignis, I left behind the unscripted cards database because Time Goddess and Flash Charge are scripted, but I need to make a new database containing Clock Lizard.

**Comment by kevinlul** [comment]
Canonical detailed explanation here: https://old.reddit.com/r/yugioh/comments/fvdn7v/presenting_project_ignis_edopro_the_opensource/fmikymf/?context=3

**Comment by kevinlul** [comment]
A version of the database is here, of course without the explanation: https://github.com/ProjectIgnis/BabelCDB/blob/258f6d19b21d2b601dea27d737caaec3df654b07/unreleased.cdb

**Comment by AlphaKretin** [comment]
Added in 2974f5a6a7c883cdc5d306346c382cd740367fe9
