### ISSUE TITLE
Improve reaction button performance

### ISSUE THREAD

**Issue by AlphaKretin** [AlphaKretin/bastion-bot#54]
Reaction buttons have various issues of varying severity.

 - [ ] One issue is that sometimes Bastion will show a "Missing Permissions" error. This seems to be on attempting to remove reactions due to a change of page, while still placing reactions for the old page. 

- [ ] In general, it may be beneficial to refactor the system so that if a button should remain on page change, but its purpose changes, we can do that without deleting and readding the button. This will reduce conflicts and waiting time.

- [ ] Bastion does not react to the removal of a reaction, even though to an end-user that's still the same action of clicking the button.

 - [ ] Bastion should accept the actual number displayed when calling a result through a command, instead of only `modulo 10`.

**Comment by kevinlul** [comment]
This is solved by message components (buttons), which will be used in DawnbrandBots/bastion-bot#343
