### ISSUE TITLE
Filter searches by banlist status

### ISSUE THREAD

**Issue by AlphaKretin** [AlphaKretin/bastion-bot#57]
I previously tried to implement this in the past, but the decoupling of banlist information from the CDB means it massively increased overhead and slowed down searches. I may need to refactor how they're handled in general, especially with the new support for multiple banlists.

**Comment by kevinlul** [comment]
This is possible in the `.match` and `.search` replacement (DawnbrandBots/bastion-bot#343) as long as the limit regulation continues to be part of the card documents. Currently, it supports searching for `limit_regulation.tcg:Limited` and similar.
