### ISSUE TITLE
Option to combine searches

### ISSUE THREAD

**Issue by AlphaKretin** [AlphaKretin/bastion-bot#61]
For example, take a previous set of results and apply an additional filter to it. This will also allow searching for results that match multiple phrases, or adding a text search to a name match.

**Comment by kevinlul** [comment]
[Lucene query strings](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-query-string-query.html#query-string-syntax) in the replacement command (DawnbrandBots/bastion-bot#343) support much more complex and nested logic, which covers this use case.
