### ISSUE TITLE
.match should have a back button

### ISSUE THREAD

**Issue by shli3** [AlphaKretin/bastion-bot#76]
When using the .match command, you can move forward but not backward, having a way to move back would be really beneficial for searches that bring up a low of data.

**Comment by AlphaKretin** [comment]
Hi, thanks for the feedback. The match command is supposed to have a back button, but unfortunately, Bastion's reaction buttons are quite buggy so they don't properly reload after you move to a page that needs a back button. Improving that whole system is covered by issue #54 so I'm going to treat this as a duplicate.

**Comment by shli3** [comment]
Fair enough!
