### ISSUE TITLE
Artwork Search function

### ISSUE THREAD

**Issue by buh2** [AlphaKretin/bastion-bot#77]
I would love if the bot had a function that allowed you to search for a cards full artwork! The bot already shows an image of its artwork when normally searching for a card, but the image is incredibly small and often doesn't even load!

Please consider adding this!

**Comment by AlphaKretin** [comment]
If you're on PC, you can click on the thumbnail of the image in the card search to get it at full size. As far as images not loading, that's an issue with what images we have access to. We're currently working on a major update to Bastion, and when it's done we expect image performance to be more consistent, in which case we may well implement an artwork command, but the Bastion team is currently strapped for time so progress on the update is going slowly.

**Comment by buh2** [comment]
Ah, awesome! I'm excited for the big update then!

**Comment by AlphaKretin** [comment]
Hi @buh2 - the update mentioned here is currently in progress through a gradual rollout, and the new art command is something we've just finished and deployed. We're still working on things like improving the card search and completeness of what art we have, but you should be able to search for card art now using the `/art` Slash Command.

**Comment by buh2** [comment]
Oh, awesome!

I'm glad it's finally here. I will try it out today. Thanks a lot guys. :)
