### ISSUE TITLE
Not working at all in threads

### ISSUE THREAD

**Issue by MKhayle** [AlphaKretin/bastion-bot#78]
Bastion's features do not work in threads from what I experienced, even though it's been summoned within said thread by mentionning it. 

![image](https://user-images.githubusercontent.com/4359469/133740743-9112bcf2-c9f1-498a-ad76-1579c7b44726.png)

**Comment by AlphaKretin** [comment]
The current framework Bastion uses to work as a Discord bot doesn't support threads. We're currently working on a major update that will include switching over to a framework with thread support, but the team is strapped for time so progress is slow going. Until then, there's not much that can be done about it.
